//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int CitaID { get; set; }
        public string CoordinadorID { get; set; }
        public System.TimeSpan Hora { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Estado { get; set; }
        public string Mensaje { get; set; }
        public string AlumnoID { get; set; }
    
        public virtual Coordinador Coordinador { get; set; }
    }
}
