//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoordinacionEntities : DbContext
    {
        public CoordinacionEntities()
            : base("name=CoordinacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<CarreraMaestro> CarreraMaestro { get; set; }
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Coordinador> Coordinador { get; set; }
        public virtual DbSet<DiaMateria> DiaMateria { get; set; }
        public virtual DbSet<Grupo> Grupo { get; set; }
        public virtual DbSet<HorarioAlumno> HorarioAlumno { get; set; }
        public virtual DbSet<Maestro> Maestro { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<MateriaDelGrupo> MateriaDelGrupo { get; set; }
        public virtual DbSet<MateriasSemestre> MateriasSemestre { get; set; }
        public virtual DbSet<Reticula> Reticula { get; set; }
        public virtual DbSet<ReticulaMateria> ReticulaMateria { get; set; }
        public virtual DbSet<Semestre> Semestre { get; set; }
        public virtual DbSet<SemestreHorario> SemestreHorario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
