//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReticulaMateria
    {
        public int ReiticulaMateriaID { get; set; }
        public string ReticulaID { get; set; }
        public string MateriaID { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Materia Materia { get; set; }
        public virtual Reticula Reticula { get; set; }
    }
}
