//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemestreHorario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SemestreHorario()
        {
            this.MateriasSemestre = new HashSet<MateriasSemestre>();
        }
    
        public int ID { get; set; }
        public string CoordinadorID { get; set; }
        public int SemestreID { get; set; }
        public string Año { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual Coordinador Coordinador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MateriasSemestre> MateriasSemestre { get; set; }
        public virtual Semestre Semestre { get; set; }
    }
}
